services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app          # mounts your local code into the container
      - /app/node_modules  # prevents overwriting container node_modules
    environment:
      - NODE_ENV=development
